---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
  - name: bosh-cli
  - name: bosh-src
  - name: environment
  - name: director-state

params:
  STEMCELL_NAME: null

outputs:
  - name: bats-config

run:
  path: bosh-src/ci/bats/iaas/vsphere/prepare-bats-config.sh
