---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
  - name: director-state
  - name: bosh-src
  - name: bosh-cli

run:
  path: bosh-src/ci/bats/tasks/destroy-director.sh
