---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk

inputs:
  - name: bosh-src
  - name: terraform-output

run:
  path: bosh-src/ci/tasks/create-brats-sql-users.sh

params:
  GOOGLE_CREDENTIALS: replace-me
  GCP_POSTGRES_USERNAME: replace-me
  GCP_POSTGRES_PASSWORD: replace-me
  GCP_MYSQL_USERNAME: replace-me
  GCP_MYSQL_PASSWORD: replace-me
