---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: version
- name: bosh-src
- name: stemcell

outputs:
- name: compiled-release
- name: metalink-path

run:
  path: bosh-src/ci/tasks/export-final-release.sh
