---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: bosh-src
- name: release
- name: stemcell

outputs:
- name: compiled-release

run:
  path: bosh-src/ci/tasks/export-release.sh
