---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
  - name: bosh-main
  - name: bosh-cli
  - name: version
  - name: release-tarball

outputs:
  - name: bosh-main

params:
  BLOBSTORE_ACCESS_KEY_ID: replace-me
  BLOBSTORE_SECRET_ACCESS_KEY: replace-me

run:
  path: bosh-main/ci/tasks/finalize-bosh-release.sh
