---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
- name: bosh-src
- name: database-metadata
- name: gcp-ssl-config

run:
  path: bosh-src/ci/tasks/test-brats-db-cleanup.sh

params:
  RDS_MYSQL_EXTERNAL_DB_HOST: replace-me
  RDS_MYSQL_EXTERNAL_DB_USER: replace-me
  RDS_MYSQL_EXTERNAL_DB_PASSWORD: replace-me
  RDS_MYSQL_EXTERNAL_DB_NAME: replace-me
  RDS_POSTGRES_EXTERNAL_DB_HOST: replace-me
  RDS_POSTGRES_EXTERNAL_DB_USER: replace-me
  RDS_POSTGRES_EXTERNAL_DB_PASSWORD: replace-me
  RDS_POSTGRES_EXTERNAL_DB_NAME: replace-me
  GCP_MYSQL_EXTERNAL_DB_HOST: replace-me
  GCP_MYSQL_EXTERNAL_DB_USER: replace-me
  GCP_MYSQL_EXTERNAL_DB_PASSWORD: replace-me
  GCP_MYSQL_EXTERNAL_DB_NAME: replace-me
  GCP_POSTGRES_EXTERNAL_DB_HOST: replace-me
  GCP_POSTGRES_EXTERNAL_DB_USER: replace-me
  GCP_POSTGRES_EXTERNAL_DB_PASSWORD: replace-me
  GCP_POSTGRES_EXTERNAL_DB_NAME: replace-me
  GCP_PRIVATE_NETWORK_NAME: replace-me
